### ISSUE TITLE
Use NotAllowedError instead of PermissionDeniedError

### ISSUE THREAD

**Issue by mounirlamouri** [WICG/BackgroundSync#124]
The spec is using `PermissionDeniedError` which isn't defined in WebIDl. Wouldn't it make more sense to use `NotAllowedError`. Also, it would allow the error to be more generic than the user. The user agent or the system might apply restrictions.

**Comment by jkarlin** [comment]
Makes sense to me, will Push do the same?

**Comment by marcoscaceres** [comment]
I can live with `NotAllowedError`, but we should take a hard look at if `PermissionDeniedError` would occur distinctly from `NotAllowedError`.

**Comment by mvano** [comment]
Why not formalize PermissionDeniedError (just like was done for NotAllowedError recently) instead of changing the API?

**Comment by annevk** [comment]
Because having many subtly different exception types isn't doing anyone any favors.

**Comment by marcoscaceres** [comment]
> On 16 Mar 2016, at 9:26 PM, Anne van Kesteren <notifications@github.com> wrote:
> 
> Because having many subtly different exception types isn't doing anyone any favors.
> 
Agree with @annevk; the current set of errors can usually be contextualized to fit most situations (if you squint just right) - which explains why so few new ones have been minted over the years.
