### ISSUE TITLE
Not working with Chrome Version 52.0.2743.82 m

### ISSUE THREAD

**Issue by davidwu220** [WICG/BackgroundSync#129]
Background sync seems to be broken starting this week (not sure of the exact time). It always fires the 'sync' event no matter I'm online or offline. First the 'offline' button in the chrome dev tool stopped working and then this. Not sure if it's a chome update that broke it or not.

**Comment by mkruisselbrink** [comment]
You should file bugs you encounter in a specific implementation with that implementation. So in the case of the chrome implementation https://crbug.com/new would be the place to file a bug. When you do file a bug there, it would be helpful to provide as much detail as possible about what you're seeing and what you're expecting, preferably with code that reproduces the problem for you.
