### ISSUE TITLE
Explainer: what is an UA?

### ISSUE THREAD

**Issue by BairDev** [WICG/BackgroundSync#136]
Maybe I'm gifted in stupidity, but what does the abbreviation *UA* refer to [here](https://github.com/WICG/BackgroundSync/blob/master/explainer.md)?

Apart from that I guess, that *SW* means *Service Worker* in this context.

**Comment by annevk** [comment]
User agent, but both that and SW should indeed be spelled out and not abbreviated.

**Comment by houstonsmile84** [comment]
UA Local 136

**Comment by houstonsmile84** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&url=http://ualocal136.org/&ved=0ahUKEwjryoHsoPLSAhUo7oMKHVURANkQFgihATAT&usg=AFQjCNHmSel8ewDCSa7eQqXBnZQQkL7xHQ&sig2=arGlOOJ5VW2VM5Je3MHYyw

**Comment by jakearchibald** [comment]
Apologies for the spam, unfortunately I don't have the rights to delete comments. Trying to get that fixed. https://discourse.wicg.io/t/admin-rights-in-wicg-repos/2090.

Pseudo-self assigning the abbreviation issue. Will fix.

**Comment by jakearchibald** [comment]
https://github.com/WICG/BackgroundSync/pull/138 - but it seems I don't have the ability to merge.

**Comment by jakearchibald** [comment]
Merged!
