### ISSUE TITLE
Background sync with a monstrous delay

### ISSUE THREAD

**Issue by TheoneLucas** [WICG/BackgroundSync#144]
Hi, I'm facing a strange problem, I have a PWA which post some data to my web server using background sync in order to guarantee that the data are actually being saved. But, If I disconnect the internet, add the data to the queue (IndexedDB), and reconnect the internet, the request isn't made, or sometimes it is made 10, 20 minutes after I reconnect the internet. This is happening with a lot of different devices with different types of connection and networks. As I can see in this [video](https://www.youtube.com/watch?v=l4e_LFozK2k), the request is made as soon as the network is reconnected. I don't know if this is the normal behavior, I hope so, but it isn't what happens with me. I think that the browser or whoever is delaying my requests shouldn't wait more than a few seconds after the network change from offline to online to give it another try.

[I've uploaded a video to youtube which shows what I've explained](https://www.youtube.com/watch?v=1HP628isfu8). In the video, I was connected to the internet by cable, broadband, throttling it to "Fast 3G". First, I sent a normal request, with a normal internet connection, then I disconnect the internet by marking the checkbox "Offline" in chrome and add a item to the queue at 22:00:19.941, what returns an network error, then I re-connect the internet 12 seconds later and the browser only will try to make another request at 22:08:40.744, 8:09 minutes after reconnecting the internet. You can measure those times by looking at the upload flag next to the green item that I clicked and by the timestamps in the console, logging the process of adding the item to the queue (IndexedDB), saying to the SW to process it, the SW getting the message to process and actually processing it.

I've testing using:
Chrome 58.0.3029.83 on a moto Z;
Chrome 60.0.3107.4 (Official Build) dev (64-bit) on a GNU/Linux machine;

I don't know if I'm missing a point in the Background Sync Spec or if I'm doing anything wrong, what would be the same lol. If there's any typo in the text, sorry, I'm not fluent in english. Thanks in advance!

**Comment by jknox1988** [comment]
I am also having this issue.

**Comment by jkarlin** [comment]
Hi there. These are chrome implementation concerns and not spec (what this repository is) concerns. For chrome concerns, please file a bug at crbug.com with component Blink>BackgroundSync. Thanks!
