### ISSUE TITLE
Paper on abuse of Period Sync

### ISSUE THREAD

**Issue by mhofman** [WICG/BackgroundSync#150]
Looks like a [paper](https://arxiv.org/pdf/1810.00464.pdf) is making the rounds and triggered a news article on [ZDNet](https://www.zdnet.com/article/new-browser-attack-lets-hackers-run-bad-code-even-after-users-leave-a-web-page/) about abusing the periodicSync API to allow malware stealth and persistence.

There seem to be a lot of misinformation through both the paper and news article, but someone might want to get ahead of it now.

It seems that the paper was also presented this morning at a [security symposium ](https://www.ndss-symposium.org/ndss2019/accepted-papers/), but without a video, I don't know what exactly was said.

**Comment by jakearchibald** [comment]
The periodic sync API didn't get beyond a sketch. It isn't in any browser.

**Comment by mhofman** [comment]
I know that, but that paper and article claim to be using it to achieve persistence. There is no sample code so I don't know what they're actually doing. IMO it's spreading FUD on ServiceWorker in general which may be damaging to the technology.

**Comment by mhofman** [comment]
Also the MDN documentation claims it's actually shipped in Chrome.

**Comment by jakearchibald** [comment]
I've posted https://twitter.com/jaffathecake/status/1100319347304734721 to try and clear things up.
