### ISSUE TITLE
SyncManager.register / SyncManager.getTags never resolves

### ISSUE THREAD

**Issue by PatrickSachs** [WICG/BackgroundSync#153]
Hello there,

I'm having some issues on getting background sync to work reliably - it gives of a really fragile vibe at the moment:

More often than not the SyncManager.register Promise never resolves. I've tried switching networks while it is running, turning WiFi on and off or simply waiting half an hour - nothing.
Are there any reasons under which it would lock itself in an infinite loop/etc?  - Tested under Chrome 75.0.3770.101 on Android 7.0 while connected to the debugger as a remote device

```js
const tag = "api-sync:status";
console.log("will sync:", tag);
await sw.sync.register(tag);
console.log("sync is ok:", tag); // Never logged
```

So far I haven't had any luck getting it to work on a desktop OS at all, but that is most likely another issue, and far less pressing.

If required I can try to create a stripped down example repo, but I'd prefer not to since the project is proprietary.

Thanks for your time.

**Comment by wanderview** [comment]
Its possible you are seeing crbug.com/971505 which is fixed in chrome 77.

**Comment by PatrickSachs** [comment]
Thank you very much. It seems to work in Chrome Dev (which is 77.0.3865.11).

What is the current recommendation on background sync regarding user facing applications? I don't mind it being Chrome exclusive for the time being given Chromes massive market share, but I do mind inconsistent behavior.

**Comment by wanderview** [comment]
I'm sorry, but I don't understand the question.  It seems you were hitting a chrome bug, so you will need to wait for chrome 77 to be released in early September.

As far as I can tell there isn't a bug in the spec or other browsers.  (Although I believe edge is the only other browser to implement background sync.)

**Comment by PatrickSachs** [comment]
Got it - Thanks for your quick help, you have been a massive time saver.
