### ISSUE TITLE
Suggestion: rename repo and spec to background-sync (is BackgroundSync)

### ISSUE THREAD

**Issue by foolip** [WICG/BackgroundSync#176]
For consistency with:
https://github.com/WICG/background-fetch
https://github.com/WICG/periodic-background-sync

If this spec reaches the W3C Rec track, then an eventual /TR/ name will be background-sync. There are only a handful of exceptions to this among web spec, like FileAPI IndexedDB.

Spotted because this showed up at the top of the directory listing in web-platform-tests.

**Comment by jakearchibald** [comment]
Happy to do this. Do you know if bikeshed's database will just figure it out, or are there manual steps to do?

**Comment by foolip** [comment]
@tabatkins are there any steps needed for Shepherd to scrape the new URL after a rename?

**Comment by tabatkins** [comment]
Ah yeah I need to fix it.

**Comment by foolip** [comment]
That fix would happen after a rename, right, not ahead of it? (Translation: @jakearchibald may proceed.)

**Comment by tabatkins** [comment]
yes

**Comment by foolip** [comment]
Thanks Jake! Note that the URL at the top right of https://github.com/WICG/background-sync also needs updating, and isn't in version control.

**Comment by jakearchibald** [comment]
Good catch. Updated.
